FROM node:latest as builder
WORKDIR /app
COPY frontend ./
RUN npm install
ARG VITE_APP_API_URL
RUN npm run build

RUN apt-get update && apt-get install nginx -y
RUN cp -r /app/dist/. /usr/share/nginx/html
COPY nginx.frontend.conf /etc/nginx/sites-available/default
CMD ["nginx", "-g", "daemon off;"]
