export enum OrderStatus {
  PENDING = 'PENDING',
  DOUGH_START = 'DOUGH_START',
  DOUGH_END = 'DOUGH_END',
  TOPPING_START = 'TOPPING_START',
  TOPPING_END = 'TOPPING_END',
  OVEN_START = 'OVEN_START',
  OVEN_END = 'OVEN_END',
  WAITER_START = 'WAITER_START',
  WAITER_END = 'WAITER_END',
}
